### ISSUE TITLE
Update models and form to use URL link

### ISSUE THREAD

**Issue by jackiekazil** [PyLadiesDC/job-translations#7]
We want to make this as easy as possible for the user. 
- Remove job_description
- Remove job_qualitifications
- Add link to job posting <-- URL field 

^^ Later on, we will take that job posting and parse the text.

**Comment by JAStark** [comment]
remove email, too? or keep that for now?
(that does sound much simpler!)

**Comment by jackiekazil** [comment]
*\* corrected *\* 
No, do not remove, but make that optional... if someone wants to provide it for notification, then they can, otherwise they don't have to.
